version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowexa_app
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9500:8000"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    networks:
      - flowexa_network

  redis:
    image: redis:alpine
    container_name: flowexa_redis
    restart: unless-stopped
    networks:
      - flowexa_network

networks:
  flowexa_network:
    driver: bridge
