<?php

return [
    'AED' => ['code' => 'AED', 'name' => 'United Arab Emirates Dirham', 'sign' => 'د.إ'],
    'AFN' => ['code' => 'AFN', 'name' => 'Afghan Afghani', 'sign' => '؋'],
    'ALL' => ['code' => 'ALL', 'name' => 'Albanian Lek', 'sign' => 'L'],
    'AMD' => ['code' => 'AMD', 'name' => 'Armenian Dram', 'sign' => '֏'],
    'ANG' => ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder', 'sign' => 'ƒ'],
    'AOA' => ['code' => 'AOA', 'name' => 'Angolan Kwanza', 'sign' => 'Kz'],
    'ARS' => ['code' => 'ARS', 'name' => 'Argentine Peso', 'sign' => '$'],
    'AUD' => ['code' => 'AUD', 'name' => 'Australian Dollar', 'sign' => 'A$'],
    'AWG' => ['code' => 'AWG', 'name' => 'Aruban Florin', 'sign' => 'ƒ'],
    'AZN' => ['code' => 'AZN', 'name' => 'Azerbaijani Manat', 'sign' => '₼'],
    'BAM' => ['code' => 'BAM', 'name' => 'Bosnia-Herzegovina Convertible Mark', 'sign' => 'KM'],
    'BBD' => ['code' => 'BBD', 'name' => 'Barbadian Dollar', 'sign' => '$'],
    'BDT' => ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'sign' => '৳'],
    'BGN' => ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'sign' => 'лв'],
    'BHD' => ['code' => 'BHD', 'name' => 'Bahraini Dinar', 'sign' => '.د.ب'],
    'BIF' => ['code' => 'BIF', 'name' => 'Burundian Franc', 'sign' => 'FBu'],
    'BMD' => ['code' => 'BMD', 'name' => 'Bermudan Dollar', 'sign' => '$'],
    'BND' => ['code' => 'BND', 'name' => 'Brunei Dollar', 'sign' => '$'],
    'BOB' => ['code' => 'BOB', 'name' => 'Bolivian Boliviano', 'sign' => 'Bs.'],
    'BRL' => ['code' => 'BRL', 'name' => 'Brazilian Real', 'sign' => 'R$'],
    'BSD' => ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'sign' => '$'],
    'BTN' => ['code' => 'BTN', 'name' => 'Bhutanese Ngultrum', 'sign' => 'Nu.'],
    'BWP' => ['code' => 'BWP', 'name' => 'Botswanan Pula', 'sign' => 'P'],
    'BYN' => ['code' => 'BYN', 'name' => 'Belarusian Ruble', 'sign' => 'Br'],
    'BZD' => ['code' => 'BZD', 'name' => 'Belize Dollar', 'sign' => 'BZ$'],
    'CAD' => ['code' => 'CAD', 'name' => 'Canadian Dollar', 'sign' => 'C$'],
    'CDF' => ['code' => 'CDF', 'name' => 'Congolese Franc', 'sign' => 'FC'],
    'CHF' => ['code' => 'CHF', 'name' => 'Swiss Franc', 'sign' => 'CHF'],
    'CLP' => ['code' => 'CLP', 'name' => 'Chilean Peso', 'sign' => '$'],
    'CNY' => ['code' => 'CNY', 'name' => 'Chinese Yuan', 'sign' => '¥'],
    'COP' => ['code' => 'COP', 'name' => 'Colombian Peso', 'sign' => '$'],
    'CRC' => ['code' => 'CRC', 'name' => 'Costa Rican Colón', 'sign' => '₡'],
    'CUP' => ['code' => 'CUP', 'name' => 'Cuban Peso', 'sign' => '$'],
    'CVE' => ['code' => 'CVE', 'name' => 'Cape Verdean Escudo', 'sign' => '$'],
    'CZK' => ['code' => 'CZK', 'name' => 'Czech Koruna', 'sign' => 'Kč'],
    'DJF' => ['code' => 'DJF', 'name' => 'Djiboutian Franc', 'sign' => 'Fdj'],
    'DKK' => ['code' => 'DKK', 'name' => 'Danish Krone', 'sign' => 'kr'],
    'DOP' => ['code' => 'DOP', 'name' => 'Dominican Peso', 'sign' => 'RD$'],
    'DZD' => ['code' => 'DZD', 'name' => 'Algerian Dinar', 'sign' => 'د.ج'],
    'EGP' => ['code' => 'EGP', 'name' => 'Egyptian Pound', 'sign' => '£'],
    'ERN' => ['code' => 'ERN', 'name' => 'Eritrean Nakfa', 'sign' => 'Nfk'],
    'ETB' => ['code' => 'ETB', 'name' => 'Ethiopian Birr', 'sign' => 'Br'],
    'EUR' => ['code' => 'EUR', 'name' => 'Euro', 'sign' => '€'],
    'FJD' => ['code' => 'FJD', 'name' => 'Fijian Dollar', 'sign' => '$'],
    'FKP' => ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'sign' => '£'],
    'GBP' => ['code' => 'GBP', 'name' => 'British Pound', 'sign' => '£'],
    'GEL' => ['code' => 'GEL', 'name' => 'Georgian Lari', 'sign' => '₾'],
    'GHS' => ['code' => 'GHS', 'name' => 'Ghanaian Cedi', 'sign' => 'GH₵'],
    'GIP' => ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'sign' => '£'],
    'GMD' => ['code' => 'GMD', 'name' => 'Gambian Dalasi', 'sign' => 'D'],
    'GNF' => ['code' => 'GNF', 'name' => 'Guinean Franc', 'sign' => 'FG'],
    'GTQ' => ['code' => 'GTQ', 'name' => 'Guatemalan Quetzal', 'sign' => 'Q'],
    'GYD' => ['code' => 'GYD', 'name' => 'Guyanaese Dollar', 'sign' => '$'],
    'HKD' => ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'sign' => 'HK$'],
    'HNL' => ['code' => 'HNL', 'name' => 'Honduran Lempira', 'sign' => 'L'],
    'HRK' => ['code' => 'HRK', 'name' => 'Croatian Kuna', 'sign' => 'kn'],
    'HTG' => ['code' => 'HTG', 'name' => 'Haitian Gourde', 'sign' => 'G'],
    'HUF' => ['code' => 'HUF', 'name' => 'Hungarian Forint', 'sign' => 'Ft'],
    'IDR' => ['code' => 'IDR', 'name' => 'Indonesian Rupiah', 'sign' => 'Rp'],
    'ILS' => ['code' => 'ILS', 'name' => 'Israeli New Shekel', 'sign' => '₪'],
    'INR' => ['code' => 'INR', 'name' => 'Indian Rupee', 'sign' => '₹'],
    'IQD' => ['code' => 'IQD', 'name' => 'Iraqi Dinar', 'sign' => 'ع.د'],
    'IRR' => ['code' => 'IRR', 'name' => 'Iranian Rial', 'sign' => '﷼'],
    'ISK' => ['code' => 'ISK', 'name' => 'Icelandic Króna', 'sign' => 'kr'],
    'JMD' => ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'sign' => 'J$'],
    'JOD' => ['code' => 'JOD', 'name' => 'Jordanian Dinar', 'sign' => 'د.ا'],
    'JPY' => ['code' => 'JPY', 'name' => 'Japanese Yen', 'sign' => '¥'],
    'KES' => ['code' => 'KES', 'name' => 'Kenyan Shilling', 'sign' => 'KSh'],
    'KGS' => ['code' => 'KGS', 'name' => 'Kyrgystani Som', 'sign' => 'лв'],
    'KHR' => ['code' => 'KHR', 'name' => 'Cambodian Riel', 'sign' => '៛'],
    'KMF' => ['code' => 'KMF', 'name' => 'Comorian Franc', 'sign' => 'CF'],
    'KPW' => ['code' => 'KPW', 'name' => 'North Korean Won', 'sign' => '₩'],
    'KRW' => ['code' => 'KRW', 'name' => 'South Korean Won', 'sign' => '₩'],
    'KWD' => ['code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'sign' => 'د.ك'],
    'KYD' => ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'sign' => '$'],
    'KZT' => ['code' => 'KZT', 'name' => 'Kazakhstani Tenge', 'sign' => '₸'],
    'LAK' => ['code' => 'LAK', 'name' => 'Laotian Kip', 'sign' => '₭'],
    'LBP' => ['code' => 'LBP', 'name' => 'Lebanese Pound', 'sign' => 'ل.ل'],
    'LKR' => ['code' => 'LKR', 'name' => 'Sri Lankan Rupee', 'sign' => '₨'],
    'LRD' => ['code' => 'LRD', 'name' => 'Liberian Dollar', 'sign' => '$'],
    'LSL' => ['code' => 'LSL', 'name' => 'Lesotho Loti', 'sign' => 'L'],
    'LYD' => ['code' => 'LYD', 'name' => 'Libyan Dinar', 'sign' => 'ل.د'],
    'MAD' => ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'sign' => 'د.م.'],
    'MDL' => ['code' => 'MDL', 'name' => 'Moldovan Leu', 'sign' => 'L'],
    'MGA' => ['code' => 'MGA', 'name' => 'Malagasy Ariary', 'sign' => 'Ar'],
    'MKD' => ['code' => 'MKD', 'name' => 'Macedonian Denar', 'sign' => 'ден'],
    'MMK' => ['code' => 'MMK', 'name' => 'Myanmar Kyat', 'sign' => 'K'],
    'MNT' => ['code' => 'MNT', 'name' => 'Mongolian Tugrik', 'sign' => '₮'],
    'MOP' => ['code' => 'MOP', 'name' => 'Macanese Pataca', 'sign' => 'MOP$'],
    'MRU' => ['code' => 'MRU', 'name' => 'Mauritanian Ouguiya', 'sign' => 'UM'],
    'MUR' => ['code' => 'MUR', 'name' => 'Mauritian Rupee', 'sign' => '₨'],
    'MVR' => ['code' => 'MVR', 'name' => 'Maldivian Rufiyaa', 'sign' => 'Rf'],
    'MWK' => ['code' => 'MWK', 'name' => 'Malawian Kwacha', 'sign' => 'MK'],
    'MXN' => ['code' => 'MXN', 'name' => 'Mexican Peso', 'sign' => '$'],
    'MYR' => ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'sign' => 'RM'],
    'MZN' => ['code' => 'MZN', 'name' => 'Mozambican Metical', 'sign' => 'MT'],
    'NAD' => ['code' => 'NAD', 'name' => 'Namibian Dollar', 'sign' => '$'],
    'NGN' => ['code' => 'NGN', 'name' => 'Nigerian Naira', 'sign' => '₦'],
    'NIO' => ['code' => 'NIO', 'name' => 'Nicaraguan Córdoba', 'sign' => 'C$'],
    'NOK' => ['code' => 'NOK', 'name' => 'Norwegian Krone', 'sign' => 'kr'],
    'NPR' => ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'sign' => '₨'],
    'NZD' => ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'sign' => 'NZ$'],
    'OMR' => ['code' => 'OMR', 'name' => 'Omani Rial', 'sign' => 'ر.ع.'],
    'PAB' => ['code' => 'PAB', 'name' => 'Panamanian Balboa', 'sign' => 'B/.'],
    'PEN' => ['code' => 'PEN', 'name' => 'Peruvian Sol', 'sign' => 'S/'],
    'PGK' => ['code' => 'PGK', 'name' => 'Papua New Guinean Kina', 'sign' => 'K'],
    'PHP' => ['code' => 'PHP', 'name' => 'Philippine Peso', 'sign' => '₱'],
    'PKR' => ['code' => 'PKR', 'name' => 'Pakistani Rupee', 'sign' => '₨'],
    'PLN' => ['code' => 'PLN', 'name' => 'Polish Zloty', 'sign' => 'zł'],
    'PYG' => ['code' => 'PYG', 'name' => 'Paraguayan Guarani', 'sign' => '₲'],
    'QAR' => ['code' => 'QAR', 'name' => 'Qatari Rial', 'sign' => 'ر.ق'],
    'RON' => ['code' => 'RON', 'name' => 'Romanian Leu', 'sign' => 'lei'],
    'RSD' => ['code' => 'RSD', 'name' => 'Serbian Dinar', 'sign' => 'дин.'],
    'RUB' => ['code' => 'RUB', 'name' => 'Russian Ruble', 'sign' => '₽'],
    'RWF' => ['code' => 'RWF', 'name' => 'Rwandan Franc', 'sign' => 'FRw'],
    'SAR' => ['code' => 'SAR', 'name' => 'Saudi Riyal', 'sign' => 'ر.س'],
    'SBD' => ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'sign' => '$'],
    'SCR' => ['code' => 'SCR', 'name' => 'Seychellois Rupee', 'sign' => '₨'],
    'SDG' => ['code' => 'SDG', 'name' => 'Sudanese Pound', 'sign' => 'ج.س.'],
    'SEK' => ['code' => 'SEK', 'name' => 'Swedish Krona', 'sign' => 'kr'],
    'SGD' => ['code' => 'SGD', 'name' => 'Singapore Dollar', 'sign' => 'S$'],
    'SHP' => ['code' => 'SHP', 'name' => 'St. Helena Pound', 'sign' => '£'],
    'SLL' => ['code' => 'SLL', 'name' => 'Sierra Leonean Leone', 'sign' => 'Le'],
    'SOS' => ['code' => 'SOS', 'name' => 'Somali Shilling', 'sign' => 'S'],
    'SRD' => ['code' => 'SRD', 'name' => 'Surinamese Dollar', 'sign' => '$'],
    'SSP' => ['code' => 'SSP', 'name' => 'South Sudanese Pound', 'sign' => '£'],
    'STN' => ['code' => 'STN', 'name' => 'São Tomé & Príncipe Dobra', 'sign' => 'Db'],
    'SVC' => ['code' => 'SVC', 'name' => 'Salvadoran Colón', 'sign' => '$'],
    'SYP' => ['code' => 'SYP', 'name' => 'Syrian Pound', 'sign' => '£'],
    'SZL' => ['code' => 'SZL', 'name' => 'Swazi Lilangeni', 'sign' => 'L'],
    'THB' => ['code' => 'THB', 'name' => 'Thai Baht', 'sign' => '฿'],
    'TJS' => ['code' => 'TJS', 'name' => 'Tajikistani Somoni', 'sign' => 'SM'],
    'TMT' => ['code' => 'TMT', 'name' => 'Turkmenistani Manat', 'sign' => 'T'],
    'TND' => ['code' => 'TND', 'name' => 'Tunisian Dinar', 'sign' => 'د.ت'],
    'TOP' => ['code' => 'TOP', 'name' => 'Tongan Paʻanga', 'sign' => 'T$'],
    'TRY' => ['code' => 'TRY', 'name' => 'Turkish Lira', 'sign' => '₺'],
    'TTD' => ['code' => 'TTD', 'name' => 'Trinidad & Tobago Dollar', 'sign' => 'TT$'],
    'TWD' => ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'sign' => 'NT$'],
    'TZS' => ['code' => 'TZS', 'name' => 'Tanzanian Shilling', 'sign' => 'TSh'],
    'UAH' => ['code' => 'UAH', 'name' => 'Ukrainian Hryvnia', 'sign' => '₴'],
    'UGX' => ['code' => 'UGX', 'name' => 'Ugandan Shilling', 'sign' => 'USh'],
    'USD' => ['code' => 'USD', 'name' => 'US Dollar', 'sign' => '$'],
    'UYU' => ['code' => 'UYU', 'name' => 'Uruguayan Peso', 'sign' => '$U'],
    'UZS' => ['code' => 'UZS', 'name' => 'Uzbekistani Som', 'sign' => 'so\'m'],
    'VES' => ['code' => 'VES', 'name' => 'Venezuelan Bolívar', 'sign' => 'Bs.S.'],
    'VND' => ['code' => 'VND', 'name' => 'Vietnamese Dong', 'sign' => '₫'],
    'VUV' => ['code' => 'VUV', 'name' => 'Vanuatu Vatu', 'sign' => 'VT'],
    'WST' => ['code' => 'WST', 'name' => 'Samoan Tala', 'sign' => 'WS$'],
    'XAF' => ['code' => 'XAF', 'name' => 'Central African CFA Franc', 'sign' => 'FCFA'],
    'XCD' => ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'sign' => '$'],
    'XOF' => ['code' => 'XOF', 'name' => 'West African CFA Franc', 'sign' => 'CFA'],
    'XPF' => ['code' => 'XPF', 'name' => 'CFP Franc', 'sign' => '₣'],
    'YER' => ['code' => 'YER', 'name' => 'Yemeni Rial', 'sign' => '﷼'],
    'ZAR' => ['code' => 'ZAR', 'name' => 'South African Rand', 'sign' => 'R'],
    'ZMW' => ['code' => 'ZMW', 'name' => 'Zambian Kwacha', 'sign' => 'ZK'],
    'ZWL' => ['code' => 'ZWL', 'name' => 'Zimbabwean Dollar', 'sign' => 'Z$'],
];
